export default {
  FETCH_JOB_ASSISTANCE: 'FETCH_JOB_ASSISTANCE',
  ON_FETCH_JOB_ASSISTANCE_SUCCESS: 'ON_FETCH_JOB_ASSISTANCE_SUCCESS',
  ON_FETCH_JOB_ASSISTANCE_ERROR: 'ON_FETCH_JOB_ASSISTANCE_ERROR',
};
