export default {
  FETCH_WHATYOUNEED_SERVICES: 'FETCH_WHATYOUNEED_SERVICES',
  ON_FETCH_WHATYOUNEED_SERVICES_SUCCESS: 'ON_FETCH_WHATYOUNEED_SERVICES_SUCCESS',
  ON_FETCH_WHATYOUNEED_SERVICES_ERROR: 'ON_FETCH_WHATYOUNEED_SERVICES_ERROR',
};
