export default {
  FETCH_HOME_SERVICES: 'FETCH_HOME_SERVICES',
  GET_BANNERS: 'GET_BANNERS',
  GET_EVENTS: 'GET_EVENTS',
  ON_FETCH_HOME_SERVICES_SUCCESS: 'ON_FETCH_HOME_SERVICES_SUCCESS',
  ON_GET_BANNERS_SUCCESS: 'ON_GET_BANNERS_SUCCESS',
  ON_GET_EVENTS_SUCCESS: 'ON_GET_EVENTS_SUCCESS',
  ON_FETCH_HOME_SERVICES_ERROR: 'ON_FETCH_HOME_SERVICES_ERROR',
  ON_GET_BANNERS_ERROR: 'ON_GET_BANNERS_ERROR',
  ON_GET_EVENTS_ERROR: 'ON_GET_EVENTS_ERROR',
  GET_UNREAD_NOTIFICATION_COUNT: 'GET_UNREAD_NOTIFICATION_COUNT',
  ON_GET_UNREAD_NOTIFICATION_COUNT_SUCCESS:
    'ON_GET_UNREAD_NOTIFICATION_COUNT_SUCCESS',
  ON_GET_UNREAD_NOTIFICATION_COUNT_ERROR:
    'ON_GET_UNREAD_NOTIFICATION_COUNT_ERROR',
};
