export default {
  SET_LANGUAGE: 'SET_LANGUAGE',
  SET_ACTIVE_DRAWER: 'SET_ACTIVE_DRAWER',
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  ON_FETCH_SETTINGS_SUCCESS: 'ON_FETCH_SETTINGS_SUCCESS',
  ON_FETCH_SETTINGS_ERROR: 'ON_FETCH_SETTINGS_ERROR',
  SET_LOCATION: 'SET_LOCATION',
  SET_NET_STATUS: 'SET_NET_STATUS',
  SET_TOKEN: 'SET_TOKEN',
  SHOW_TOAST: 'SHOW_TOAST'
};
