export default {
  FETCH_DETAILED_NOTIFICATION: 'FETCH_DETAILED_NOTIFICATION',
  ON_FETCH_DETAILED_NOTIFICATION_SUCCESS:
    'ON_FETCH_DETAILED_NOTIFICATION_SUCCESS',
  ON_FETCH_DETAILED_NOTIFICATION_ERROR: 'ON_FETCH_DETAILED_NOTIFICATION_ERROR',
};
