export default {
  FETCH_WHATYOUNEED_SERVICE_DATA: 'FETCH_WHATYOUNEED_SERVICE_DATA',
  ON_FETCH_WHATYOUNEED_SERVICE_DATA_SUCCESS: 'ON_FETCH_WHATYOUNEED_SERVICE_DATA_SUCCESS',
  ON_FETCH_WHATYOUNEED_SERVICE_DATA_ERROR: 'ON_FETCH_WHATYOUNEED_SERVICE_DATA_ERROR',
};
