export default {
  FETCH_JOBASSISTANCE_SERVICE_DATA: 'FETCH_JOBASSISTANCE_SERVICE_DATA',
  ON_FETCH_JOBASSISTANCE_SERVICE_DATA_SUCCESS: 'ON_FETCH_JOBASSISTANCE_SERVICE_DATA_SUCCESS',
  ON_FETCH_JOBASSISTANCE_SERVICE_DATA_ERROR: 'ON_FETCH_JOBASSISTANCE_SERVICE_DATA_ERROR',
};
