export default {
  FETCH_SERVICE_CONTENT: 'FETCH_SERVICE_CONTENT',
  ON_FETCH_SERVICE_CONTENT_SUCCESS: 'ON_FETCH_SERVICE_CONTENT_SUCCESS',
  ON_FETCH_SERVICE_CONTENT_ERROR: 'ON_FETCH_SERVICE_CONTENT_ERROR',
  FETCH_MORE_SERVICE_CONTENT: 'FETCH_MORE_SERVICE_CONTENT',
  ON_FETCH_MORE_SERVICE_CONTENT_SUCCESS: 'ON_FETCH_MORE_SERVICE_CONTENT_SUCCESS',
  ON_FETCH_MORE_SERVICE_CONTENT_ERROR: 'ON_FETCH_MORE_SERVICE_CONTENT_ERROR',
};
