export default {
  FETCH_EMERGENCY_HELP: 'FETCH_EMERGENCY_HELP',
  ON_FETCH_EMERGENCY_HELP_SUCCESS: 'ON_FETCH_EMERGENCY_HELP_SUCCESS',
  ON_FETCH_EMERGENCY_HELP_ERROR: 'ON_FETCH_EMERGENCY_HELP_ERROR',
};
