export default {
  FETCH_NOTIFICATIONS: 'FETCH_NOTIFICATIONS',
  ON_FETCH_NOTIFICATIONS_SUCCESS: 'ON_FETCH_NOTIFICATIONS_SUCCESS',
  ON_FETCH_NOTIFICATIONS_ERROR: 'ON_FETCH_NOTIFICATIONS_ERROR',
  FETCH_MORE_NOTIFICATIONS: 'FETCH_MORE_NOTIFICATIONS',
  ON_FETCH_MORE_NOTIFICATIONS_SUCCESS: 'ON_FETCH_MORE_NOTIFICATIONS_SUCCESS',
  ON_FETCH_MORE_NOTIFICATIONS_ERROR: 'ON_FETCH_MORE_NOTIFICATIONS_ERROR',
  MARK_AS_READ: 'MARK_AS_READ',
};
