export default {
  FETCH_BUILD_YOUR_SKILLS: 'FETCH_BUILD_YOUR_SKILLS',
  ON_FETCH_BUILD_YOUR_SKILLS_SUCCESS: 'ON_FETCH_BUILD_YOUR_SKILLS_SUCCESS',
  ON_FETCH_BUILD_YOUR_SKILLS_ERROR: 'ON_FETCH_BUILD_YOUR_SKILLS_ERROR',
};
