export default {
  FETCH_SERVICE_ITEM: 'FETCH_SERVICE_ITEM',
  ON_FETCH_SERVICE_ITEM_SUCCESS: 'ON_FETCH_SERVICE_ITEM_SUCCESS',
  ON_FETCH_SERVICE_ITEM_ERROR: 'ON_FETCH_SERVICE_ITEM_ERROR',
  FETCH_MORE_SERVICE_ITEM: 'FETCH_MORE_SERVICE_ITEM',
  ON_FETCH_MORE_SERVICE_ITEM_SUCCESS: 'ON_FETCH_MORE_SERVICE_ITEM_SUCCESS',
  ON_FETCH_MORE_SERVICE_ITEM_ERROR: 'ON_FETCH_MORE_SERVICE_ITEM_ERROR',
};
