export default {
  FETCH_DETAILED_EVENT: 'FETCH_DETAILED_EVENT',
  ON_FETCH_DETAILED_EVENT_SUCCESS:
    'ON_FETCH_DETAILED_EVENT_SUCCESS',
  ON_FETCH_DETAILED_EVENT_ERROR: 'ON_FETCH_DETAILED_EVENT_ERROR',
};
