export default {
  FETCH_SERVICE_CONNECT: 'FETCH_SERVICE_CONNECT',
  ON_FETCH_SERVICE_CONNECT_SUCCESS: 'ON_FETCH_SERVICE_CONNECT_SUCCESS',
  ON_FETCH_SERVICE_CONNECT_ERROR: 'ON_FETCH_SERVICE_CONNECT_ERROR'
};
