export default {
  FETCH_LEGALINFORMATION_SERVICE_DATA: 'FETCH_LEGALINFORMATION_SERVICE_DATA',
  ON_FETCH_LEGALINFORMATION_SERVICE_DATA_SUCCESS:
    'ON_FETCH_LEGALINFORMATION_SERVICE_DATA_SUCCESS',
  ON_FETCH_LEGALINFORMATION_SERVICE_DATA_ERROR:
    'ON_FETCH_LEGALINFORMATION_SERVICE_DATA_ERROR',
};
