export default {
  FETCH_EMERGENCYHELP_SERVICE_DATA: 'FETCH_EMERGENCYHELP_SERVICE_DATA',
  ON_FETCH_EMERGENCYHELP_SERVICE_DATA_SUCCESS:
    'ON_FETCH_EMERGENCYHELP_SERVICE_DATA_SUCCESS',
  ON_FETCH_EMERGENCYHELP_SERVICE_DATA_ERROR:
    'ON_FETCH_EMERGENCYHELP_SERVICE_DATA_ERROR',
};
