export default {
  FETCH_EVENTS: 'FETCH_EVENTS',
  ON_FETCH_EVENTS_SUCCESS: 'ON_FETCH_EVENTS_SUCCESS',
  ON_FETCH_EVENTS_ERROR: 'ON_FETCH_EVENTS_ERROR',
  FETCH_MORE_EVENTS: 'FETCH_MORE_EVENTS',
  ON_FETCH_MORE_EVENTS_SUCCESS: 'ON_FETCH_MORE_EVENTS_SUCCESS',
  ON_FETCH_MORE_EVENTS_ERROR: 'ON_FETCH_MORE_EVENTS_ERROR'  
};
