export default {
  FETCH_LEGAL_INFORMATION: 'FETCH_LEGAL_INFORMATION',
  ON_FETCH_LEGAL_INFORMATION_SUCCESS: 'ON_FETCH_LEGAL_INFORMATION_SUCCESS',
  ON_FETCH_LEGAL_INFORMATION_ERROR: 'ON_FETCH_LEGAL_INFORMATION_ERROR',
};
